/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    solutions: Solution;
    references: Reference;
    posts: Post;
    media: Media;
    documents: Document;
    leads: Lead;
    events: Event;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en') | ('tr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'tr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Örn. GugaTY850. Ürün listelerinde ve tekliflerde kullanılır.
   */
  model?: string | null;
  category:
    'hardware' | 'label' | 'industrial-tag' | 'industrial-label' | 'card' | 'ribbon' | 'lanyard' | 'library' | 'retail';
  /**
   * Listelerde ve arama sonuçlarında görünür. 1-2 cümle.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ürün sayfasındaki teknik tabloyu oluşturur. İhracat müşterisinin ilk baktığı yer.
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  datasheets?: (number | Document)[] | null;
  images?: (number | Media)[] | null;
  relatedSolutions?: (number | Solution)[] | null;
  /**
   * Boşsa sayfa başlığı kullanılır. 60 karaktere kadar önerilir.
   */
  metaTitle?: string | null;
  /**
   * Boşsa özet kullanılır. 150-160 karakter idealdir.
   */
  metaDescription?: string | null;
  /**
   * Boşsa sayfanın ana görseli kullanılır.
   */
  metaImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Boş bırakılırsa başlıktan otomatik üretilir. Yayındaki bir sayfanın adresini değiştirmek bağlantıları kırar.
   */
  slug: string;
  featured?: boolean | null;
  /**
   * Küçük sayı önce gelir.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  kind?: ('datasheet' | 'catalogue' | 'certificate' | 'other') | null;
  /**
   * Bu dosyanın kaç kez indirildiği. Otomatik sayılır.
   */
  downloadCount?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görseli göremeyen ziyaretçi ve arama motorları için kısa açıklama.
   */
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  /**
   * Örn. Depo, Perakende, Sağlık. Kartlarda rozet olarak görünür.
   */
  sector?: string | null;
  excerpt: string;
  heroImage?: (number | null) | Media;
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Çözüm sayfasının ana bloğu: her madde bir başlık ve açıklama.
   */
  capabilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Örn. "%80" + "sayım süresinde azalma". Rakam olmadan ihracat müşterisi ikna olmaz.
   */
  outcomes?:
    | {
        metric: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  integrations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Boşsa sayfa başlığı kullanılır. 60 karaktere kadar önerilir.
   */
  metaTitle?: string | null;
  /**
   * Boşsa özet kullanılır. 150-160 karakter idealdir.
   */
  metaDescription?: string | null;
  /**
   * Boşsa sayfanın ana görseli kullanılır.
   */
  metaImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Boş bırakılırsa başlıktan otomatik üretilir. Yayındaki bir sayfanın adresini değiştirmek bağlantıları kırar.
   */
  slug: string;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  title: string;
  /**
   * Müşteri adı paylaşılamıyorsa boş bırakın; sektör yeterlidir.
   */
  client?: string | null;
  sector: string;
  country?: string | null;
  challenge: string;
  approach: string;
  /**
   * Rakamlı sonuç: "%80" + "sayım süresinde azalma".
   */
  results?:
    | {
        metric: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  relatedSolution?: (number | null) | Solution;
  /**
   * Boşsa sayfa başlığı kullanılır. 60 karaktere kadar önerilir.
   */
  metaTitle?: string | null;
  /**
   * Boşsa özet kullanılır. 150-160 karakter idealdir.
   */
  metaDescription?: string | null;
  /**
   * Boşsa sayfanın ana görseli kullanılır.
   */
  metaImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Boş bırakılırsa başlıktan otomatik üretilir. Yayındaki bir sayfanın adresini değiştirmek bağlantıları kırar.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Liste kartlarında ve arama sonuçlarında görünür.
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedSolutions?: (number | Solution)[] | null;
  /**
   * Boşsa sayfa başlığı kullanılır. 60 karaktere kadar önerilir.
   */
  metaTitle?: string | null;
  /**
   * Boşsa özet kullanılır. 150-160 karakter idealdir.
   */
  metaDescription?: string | null;
  /**
   * Boşsa sayfanın ana görseli kullanılır.
   */
  metaImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Boş bırakılırsa başlıktan otomatik üretilir. Yayındaki bir sayfanın adresini değiştirmek bağlantıları kırar.
   */
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Siteden gelen teklif ve iletişim talepleri. CSV dışa aktarma: /api/leads/export — tarih aralığı için ?from=2026-01-01&to=2026-01-31 ekleyin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  company?: string | null;
  email: string;
  phone?: string | null;
  country?: string | null;
  locale?: ('tr' | 'en') | null;
  message?: string | null;
  productInterest?: (number | Product)[] | null;
  sourcePath?: string | null;
  status: 'new' | 'in-progress' | 'quoted' | 'won' | 'lost' | 'spam';
  assignedTo?: (number | null) | User;
  /**
   * Yalnızca panelde görünür, siteye çıkmaz.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Ham kayıtlar. Özet için panel ana sayfasındaki grafiklere bakın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'pageview' | 'download' | 'lead';
  path: string;
  locale?: string | null;
  country?: string | null;
  referrerHost?: string | null;
  deviceType?: string | null;
  documentRef?: (number | null) | Document;
  productRef?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  model?: T;
  category?: T;
  excerpt?: T;
  body?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  datasheets?: T;
  images?: T;
  relatedSolutions?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  noIndex?: T;
  slug?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  sector?: T;
  excerpt?: T;
  heroImage?: T;
  problem?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        metric?: T;
        label?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  relatedProducts?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  noIndex?: T;
  slug?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  sector?: T;
  country?: T;
  challenge?: T;
  approach?: T;
  results?:
    | T
    | {
        metric?: T;
        label?: T;
        id?: T;
      };
  image?: T;
  relatedSolution?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  noIndex?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedSolutions?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  noIndex?: T;
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  downloadCount?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  country?: T;
  locale?: T;
  message?: T;
  productInterest?: T;
  sourcePath?: T;
  status?: T;
  assignedTo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  path?: T;
  locale?: T;
  country?: T;
  referrerHost?: T;
  deviceType?: T;
  documentRef?: T;
  productRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  legalName: string;
  brandName: string;
  /**
   * Ana sayfa başlığının altında ve paylaşımlarda görünür.
   */
  tagline?: string | null;
  logo?: (number | null) | Media;
  foundedYear?: number | null;
  /**
   * İlk sıradaki adres merkez kabul edilir ve yapılandırılmış veride kullanılır.
   */
  offices?:
    | {
        label: string;
        street: string;
        postalCode?: string | null;
        district?: string | null;
        city: string;
        country: string;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  phones?:
    | {
        label?: string | null;
        number: string;
        whatsapp?: boolean | null;
        id?: string | null;
      }[]
    | null;
  email: string;
  exportEmail?: string | null;
  exportIntro?: string | null;
  incoterms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name: string;
        document?: (number | null) | Document;
        id?: string | null;
      }[]
    | null;
  shippedCountries?:
    | {
        country: string;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: 'linkedin' | 'instagram' | 'youtube' | 'x' | 'facebook';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Örn. G-XXXXXXXXXX. Boş bırakılırsa GA yüklenmez; kendi analitiğimiz her hâlükârda çalışır.
   */
  gaMeasurementId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        /**
         * Türkçe için /urunler, İngilizce için /en/products biçiminde yazın.
         */
        href: string;
        children?:
          | {
              label: string;
              /**
               * Türkçe için /urunler, İngilizce için /en/products biçiminde yazın.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Türkçe için /urunler, İngilizce için /en/products biçiminde yazın.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  brandName?: T;
  tagline?: T;
  logo?: T;
  foundedYear?: T;
  offices?:
    | T
    | {
        label?: T;
        street?: T;
        postalCode?: T;
        district?: T;
        city?: T;
        country?: T;
        mapUrl?: T;
        id?: T;
      };
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        whatsapp?: T;
        id?: T;
      };
  email?: T;
  exportEmail?: T;
  exportIntro?: T;
  incoterms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        document?: T;
        id?: T;
      };
  shippedCountries?:
    | T
    | {
        country?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  gaMeasurementId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}